version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "53:53/udp"  # DNS port
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      yoxplore-network:
        ipv4_address: 172.22.0.2
    dns:
      - 127.0.0.1
    extra_hosts:
      - "yoxplore.id:127.0.0.1"
    cap_add:
      - NET_ADMIN
  
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ''
      MARIADB_DATABASE: yoxplore
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      yoxplore-network:
        ipv4_address: 172.22.0.3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "8080:80"
    networks:
      yoxplore-network:
        ipv4_address: 172.22.0.4
    depends_on:
      - db

networks:
  yoxplore-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

volumes:
  mariadb_data: