version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "53:53/udp"  # DNS port
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      yoxplore-network:
        ipv4_address: 172.22.0.2
    dns:
      - 127.0.0.1
    extra_hosts:
      - "yoxplore.local:127.0.0.1"
    cap_add:
      - NET_ADMIN
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: yoxplore
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      yoxplore-network:
        ipv4_address: 172.22.0.3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  yoxplore-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

volumes:
  mysql_data: