version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - yoxplore-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yoxplore
      MYSQL_USER: yoxplore
      MYSQL_PASSWORD: yoxplore123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - yoxplore-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - yoxplore-network

networks:
  yoxplore-network:
    driver: bridge

volumes:
  mysql_data: